name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        env GOOS=darwin GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.macos_amd64 ./downloader.go
        env GOOS=linux GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.linux_amd64 ./downloader.go        
        env GOOS=windows GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.windows_amd64.exe ./downloader.go        

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        if-no-files-found: warn # 'warn'
        path: ${{ github.workspace }}/bin/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: contains(github.ref, 'alpha')
        files: |
          ${{ github.workspace }}/bin/SF-Downloader.macos_amd64
          ${{ github.workspace }}/bin/SF-Downloader.linux_amd64
          ${{ github.workspace }}/bin/SF-Downloader.windows_amd64.exe

        