name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build -v -o ${{ github.workspace }}/bin/SF-Downloader ./downloader.go        
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        if-no-files-found: warn # 'warn'
        path: ${{ github.workspace }}/bin/*

#    - name: Test
#      run: go test -v ./...
