name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        env GOOS=darwin GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.macos_amd64 ./downloader.go
        env GOOS=linux GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.linux_amd64 ./downloader.go        
        env GOOS=windows GOARCH=amd64 go build -v -o ${{ github.workspace }}/bin/SF-Downloader.windows_amd64.exe ./downloader.go        

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        if-no-files-found: warn # 'warn'
        path: ${{ github.workspace }}/bin/*

    - name: Create Release
      if: ${{ success() }} && startsWith(github.ref, 'v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: not(startsWith(github.ref, 'v'))
        prerelease: contains(github.ref, 'alpha') || contains(github.ref, 'beta')

    - name: Upload Release Asset
      if: ${{ success() }}
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ github.workspace }}/bin/SF-Downloader
        asset_name: SF-Downloader
        asset_content_type: application/octet-stream